.deploy: &deploy
  before_script:
    - cat /etc/os-release
    - uname -a
    - ruby --version
    - gem --version
    - bundle --version
    - apk add --no-cache --update build-base git
    - bundle install --clean --deployment --jobs=2 --without default development lint production test
  image: ruby:alpine
  only:
    - master
  stage: deploy
  tags:
    - gitlab-org-high-cpu

.lint: &lint
  before_script:
    - cat /etc/os-release
    - uname -a
    - ruby --version
    - gem --version
    - bundle --version
    - apk add --no-cache --update git
    - bundle install --clean --deployment --jobs=2 --without default deployment development production test
  image: ruby:alpine
  stage: lint
  tags:
    - gitlab-org-high-cpu

.test: &test
  artifacts:
    expire_in: 1 day
    paths:
      - coverage
  before_script:
    - cat /etc/os-release
    - uname -a
    - ruby --version
    - gem --version
    - bundle --version
    - apk add --no-cache --update build-base git sqlite-dev tzdata xz-dev
    - bundle install --clean --deployment --jobs=2 --without deployment development lint production
  script:
    - bundle exec rake
  stage: test
  tags:
    - gitlab-org-high-cpu

.use_jruby_9_1: &use_jruby_9_1
  image: jruby:9.1-alpine

.use_mri_2_2: &use_mri_2_2
  image: ruby:2.2-alpine

.use_mri_2_3: &use_mri_2_3
  image: ruby:2.3-alpine

.use_mri_2_4: &use_mri_2_4
  image: ruby:2.4-alpine

.use_rails_4_0: &use_rails_4_0
  <<: *test
  variables:
    BUNDLE_GEMFILE: gemfiles/Gemfile.rails-4.0.x

.use_rails_4_1: &use_rails_4_1
  <<: *test
  variables:
    BUNDLE_GEMFILE: gemfiles/Gemfile.rails-4.1.x

.use_rails_4_2: &use_rails_4_2
  <<: *test
  variables:
    BUNDLE_GEMFILE: gemfiles/Gemfile.rails-4.2.x

.use_rails_5_0: &use_rails_5_0
  <<: *test
  variables:
    BUNDLE_GEMFILE: Gemfile

stages:
#  - lint
  - test
  - deploy

test:rails-5.0:mri:2.2:
  <<: *use_mri_2_2
  <<: *use_rails_5_0
  script: bundle exec rake --trace

test:rails-5.0:mri:2.3:
  <<: *use_mri_2_3
  <<: *use_rails_5_0
  script: bundle exec rake --trace

variables:
  JRUBY_OPTS: --debug
  LC_ALL: C.UTF-8
  RAILS_ENV: test
