.deploy: &deploy
  before_script:
    - cat /etc/os-release
    - uname -a
    - ruby --version
    - gem --version
    - gem install bundler
    - bundle --version
    - apk add --no-cache --update build-base git
    - bundle install --clean --deployment --jobs=2 --without default development lint production test performance
  image: ruby:alpine
  only:
    - master
  stage: deploy
  tags:
    - gitlab-org

.lint: &lint
  before_script:
    - cat /etc/os-release
    - uname -a
    - ruby --version
    - gem --version
    - gem install bundler
    - bundle --version
    - apk add --no-cache --update build-base git
    - bundle install --clean --deployment --jobs=2 --without default deployment development production test performance
  image: ruby:2.6-alpine
  stage: lint
  tags:
    - gitlab-org

.test: &test
  artifacts:
    expire_in: 1 day
    paths:
      - coverage
  after_script:
    - ./cc-test-reporter after-build -t simplecov
  before_script:
    - cat /etc/os-release
    - uname -a
    - ruby --version
    - gem --version
    - gem install bundler
    - bundle --version
    - apk add --no-cache --update build-base curl git sqlite-dev tzdata
    - bundle install --clean --deployment --jobs=2 --without deployment development lint production performance
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
  script:
    - bundle exec rake
  stage: test
  tags:
    - gitlab-org

.use_jruby_9_2: &use_jruby_9_2
  image: jruby:9.2-alpine

.use_mri_2_3: &use_mri_2_3
  image: ruby:2.3-alpine

.use_mri_2_4: &use_mri_2_4
  image: ruby:2.4-alpine

.use_mri_2_5: &use_mri_2_5
  image: ruby:2.5-alpine

.use_rails_4_2: &use_rails_4_2
  <<: *test
  variables:
    BUNDLE_GEMFILE: gemfiles/Gemfile.rails-4.2.x

.use_rails_5_0: &use_rails_5_0
  <<: *test
  variables:
    BUNDLE_GEMFILE: gemfiles/Gemfile.rails-5.0.x

.use_rails_5_1: &use_rails_5_1
  <<: *test
  variables:
    BUNDLE_GEMFILE: gemfiles/Gemfile.rails-5.1.x

.use_rails_5_2: &use_rails_5_2
  <<: *test
  variables:
    BUNDLE_GEMFILE: Gemfile

.use_rails_6_0: &use_rails_6_0
  <<: *test
  variables:
    BUNDLE_GEMFILE: gemfiles/Gemfile.rails-6.0.x

cache:
  paths:
    - vendor/bundle

lint:brakeman:
  <<: *lint
  artifacts:
    expire_in: 1 day
    paths:
      - brakeman
    when: always
  script:
    - bin/brakeman --exit-on-warn --output brakeman/index.html

lint:bundler:audit:
  <<: *lint
  script:
    - bin/bundle-audit check --update --verbose

lint:i18n:
  <<: *lint
  allow_failure: true
  script:
    - bin/i18n-tasks health

lint:rubocop:
  <<: *lint
  script:
    - bin/rubocop

pages:
  <<: *deploy
  artifacts:
    expire_in: 1 month
    paths:
      - public
  script:
    - DIR=public/$([ "$CI_COMMIT_REF_SLUG" = master ] || echo $CI_COMMIT_REF_SLUG)
    - mkdir -pv $DIR
    - mv -v brakeman $DIR
    - mv -v coverage $DIR
  except:
    - tags

stages:
  - lint
  - test
  - deploy

test:rails-4.2:jruby:9.2:
  <<: *use_jruby_9_2
  <<: *use_rails_4_2

test:rails-4.2:mri:2.3:
  <<: *use_mri_2_3
  <<: *use_rails_4_2

test:rails-4.2:mri:2.4:
  <<: *use_mri_2_4
  <<: *use_rails_4_2

test:rails-4.2:mri:2.5:
  <<: *use_mri_2_5
  <<: *use_rails_4_2

test:rails-5.0:jruby:9.2:
  <<: *use_jruby_9_2
  <<: *use_rails_5_0

test:rails-5.0:mri:2.3:
  <<: *use_mri_2_3
  <<: *use_rails_5_0

test:rails-5.0:mri:2.4:
  <<: *use_mri_2_4
  <<: *use_rails_5_0

test:rails-5.0:mri:2.5:
  <<: *use_mri_2_5
  <<: *use_rails_5_0

test:rails-5.1:jruby:9.2:
  <<: *use_jruby_9_2
  <<: *use_rails_5_1

test:rails-5.1:mri:2.3:
  <<: *use_mri_2_3
  <<: *use_rails_5_1

test:rails-5.1:mri:2.4:
  <<: *use_mri_2_4
  <<: *use_rails_5_1

test:rails-5.1:mri:2.5:
  <<: *use_mri_2_5
  <<: *use_rails_5_1

test:rails-5.2:jruby:9.2:
  <<: *use_jruby_9_2
  <<: *use_rails_5_2

test:rails-5.2:mri:2.4:
  <<: *use_mri_2_4
  <<: *use_rails_5_2

test:rails-5.2:mri:2.5:
  <<: *use_mri_2_5
  <<: *use_rails_5_2

test:rails-6.0:mri:2.5:
  <<: *use_mri_2_5
  <<: *use_rails_6_0
  allow_failure: true

variables:
  JRUBY_OPTS: --debug
  LC_ALL: C.UTF-8
  RAILS_ENV: test
