inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  Include:
    - 'gemfiles/Gemfile*'
  Exclude:
    - 'gemfiles/Gemfile*.lock'
    - 'bin/*'
    - 'lib/generators/**/templates/**/*'
    - 'vendor/bundle/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/UnusedMethodArgument:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'test/mock_app/Rakefile'

Metrics/ClassLength:
  Max: 500
  CountComments: false

Metrics/ModuleLength:
  Max: 600
  CountComments: false

Performance/RedundantMerge:
  MaxKeyValuePairs: 1

Rails:
  Enabled: true

Rails/ApplicationRecord:
  Exclude:
    - 'test/**/*'

Rails/DynamicFindBy:
  Whitelist:
    - find_by_name
    - find_by_names

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/FormatString:
  EnforcedStyle: percent

Style/HashSyntax:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/SingleLineBlockParams:
  Enabled: false

Style/SingleLineMethods:
  Exclude:
    - 'test/**/*'
