inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - 'gemfiles/Gemfile*'
  Exclude:
    - 'gemfiles/Gemfile*.lock'
    - 'bin/*'
    - 'lib/generators/**/templates/**/*'
    - 'vendor/bundle/**/*'

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/ClassLength:
  Max: 500

Metrics/ModuleLength:
  Max: 600

Performance/RedundantMerge:
  MaxKeyValuePairs: 1

Rails:
  Enabled: true

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/HashSyntax:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/SingleLineBlockParams:
  Enabled: false

Style/SingleLineMethods:
  Exclude:
    - 'test/**/*'
